formatter: "markdown table"
header-from: main.tf
output:
  file: "README.md"
  mode: inject
settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true
