formatter: "markdown table"
header-from: main.tf
footer-from: output.tf
output:
  file: "README.md"
  mode: inject
sections:
  show: 
    - header
    - providers
    - inputs
    - footer
sort:
  enabled: true
  by: name
settings:
  indent: 2
  sensitive: true
  type: true
